/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DesignsRouteImport } from './routes/designs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ConceptWalkRouteImport } from './routes/concept-walk'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AutomateRouteImport } from './routes/automate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as ApiQuotesRouteImport } from './routes/api/quotes'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiOrderRouteImport } from './routes/api/order'
import { Route as ApiMeetingsRouteImport } from './routes/api/meetings'
import { Route as ApiMeetingRouteImport } from './routes/api/meeting'
import { Route as AdminQuotesRouteImport } from './routes/admin/quotes'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignsRoute = DesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptWalkRoute = ConceptWalkRouteImport.update({
  id: '/concept-walk',
  path: '/concept-walk',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomateRoute = AutomateRouteImport.update({
  id: '/automate',
  path: '/automate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesRoute = ApiQuotesRouteImport.update({
  id: '/api/quotes',
  path: '/api/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrderRoute = ApiOrderRouteImport.update({
  id: '/api/order',
  path: '/api/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingsRoute = ApiMeetingsRouteImport.update({
  id: '/api/meetings',
  path: '/api/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingRoute = ApiMeetingRouteImport.update({
  id: '/api/meeting',
  path: '/api/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/admin/quotes',
  path: '/admin/quotes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automate': typeof AutomateRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/concept-walk': typeof ConceptWalkRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/designs': typeof DesignsRoute
  '/insights': typeof InsightsRoute
  '/intake': typeof IntakeRoute
  '/locations': typeof LocationsRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/api/meeting': typeof ApiMeetingRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/order': typeof ApiOrderRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/quotes': typeof ApiQuotesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automate': typeof AutomateRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/concept-walk': typeof ConceptWalkRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/designs': typeof DesignsRoute
  '/insights': typeof InsightsRoute
  '/intake': typeof IntakeRoute
  '/locations': typeof LocationsRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/api/meeting': typeof ApiMeetingRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/order': typeof ApiOrderRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/quotes': typeof ApiQuotesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automate': typeof AutomateRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/concept-walk': typeof ConceptWalkRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/designs': typeof DesignsRoute
  '/insights': typeof InsightsRoute
  '/intake': typeof IntakeRoute
  '/locations': typeof LocationsRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/api/meeting': typeof ApiMeetingRoute
  '/api/meetings': typeof ApiMeetingsRoute
  '/api/order': typeof ApiOrderRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/quote': typeof ApiQuoteRoute
  '/api/quotes': typeof ApiQuotesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automate'
    | '/careers'
    | '/clients'
    | '/concept-walk'
    | '/consultation'
    | '/contact'
    | '/designs'
    | '/insights'
    | '/intake'
    | '/locations'
    | '/portal'
    | '/privacy'
    | '/quote'
    | '/robots.txt'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/team'
    | '/terms'
    | '/admin/quotes'
    | '/api/meeting'
    | '/api/meetings'
    | '/api/order'
    | '/api/orders'
    | '/api/quote'
    | '/api/quotes'
    | '/legal/privacy'
    | '/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automate'
    | '/careers'
    | '/clients'
    | '/concept-walk'
    | '/consultation'
    | '/contact'
    | '/designs'
    | '/insights'
    | '/intake'
    | '/locations'
    | '/portal'
    | '/privacy'
    | '/quote'
    | '/robots.txt'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/team'
    | '/terms'
    | '/admin/quotes'
    | '/api/meeting'
    | '/api/meetings'
    | '/api/order'
    | '/api/orders'
    | '/api/quote'
    | '/api/quotes'
    | '/legal/privacy'
    | '/legal/terms'
  id:
    | '__root__'
    | '/'
    | '/automate'
    | '/careers'
    | '/clients'
    | '/concept-walk'
    | '/consultation'
    | '/contact'
    | '/designs'
    | '/insights'
    | '/intake'
    | '/locations'
    | '/portal'
    | '/privacy'
    | '/quote'
    | '/robots.txt'
    | '/search'
    | '/services'
    | '/sitemap.xml'
    | '/store'
    | '/team'
    | '/terms'
    | '/admin/quotes'
    | '/api/meeting'
    | '/api/meetings'
    | '/api/order'
    | '/api/orders'
    | '/api/quote'
    | '/api/quotes'
    | '/legal/privacy'
    | '/legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomateRoute: typeof AutomateRoute
  CareersRoute: typeof CareersRoute
  ClientsRoute: typeof ClientsRoute
  ConceptWalkRoute: typeof ConceptWalkRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  DesignsRoute: typeof DesignsRoute
  InsightsRoute: typeof InsightsRoute
  IntakeRoute: typeof IntakeRoute
  LocationsRoute: typeof LocationsRoute
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  ApiMeetingRoute: typeof ApiMeetingRoute
  ApiMeetingsRoute: typeof ApiMeetingsRoute
  ApiOrderRoute: typeof ApiOrderRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  ApiQuotesRoute: typeof ApiQuotesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designs': {
      id: '/designs'
      path: '/designs'
      fullPath: '/designs'
      preLoaderRoute: typeof DesignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept-walk': {
      id: '/concept-walk'
      path: '/concept-walk'
      fullPath: '/concept-walk'
      preLoaderRoute: typeof ConceptWalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automate': {
      id: '/automate'
      path: '/automate'
      fullPath: '/automate'
      preLoaderRoute: typeof AutomateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes': {
      id: '/api/quotes'
      path: '/api/quotes'
      fullPath: '/api/quotes'
      preLoaderRoute: typeof ApiQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/order': {
      id: '/api/order'
      path: '/api/order'
      fullPath: '/api/order'
      preLoaderRoute: typeof ApiOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meetings': {
      id: '/api/meetings'
      path: '/api/meetings'
      fullPath: '/api/meetings'
      preLoaderRoute: typeof ApiMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meeting': {
      id: '/api/meeting'
      path: '/api/meeting'
      fullPath: '/api/meeting'
      preLoaderRoute: typeof ApiMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/admin/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomateRoute: AutomateRoute,
  CareersRoute: CareersRoute,
  ClientsRoute: ClientsRoute,
  ConceptWalkRoute: ConceptWalkRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  DesignsRoute: DesignsRoute,
  InsightsRoute: InsightsRoute,
  IntakeRoute: IntakeRoute,
  LocationsRoute: LocationsRoute,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  ApiMeetingRoute: ApiMeetingRoute,
  ApiMeetingsRoute: ApiMeetingsRoute,
  ApiOrderRoute: ApiOrderRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  ApiQuotesRoute: ApiQuotesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
